apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application
  labels:
    app.kubernetes.io/name: my-application
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: my-application
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-application
    spec:
      containers:
      - image: nilebox/prometheus-example-app@sha256:dab60d038c5d6915af5bcbe5f0279a22b95a8c8be254153e22d7cd81b21b84c5 # Fixed!
        name: prom-example
        ports:
        - name: metrics
          containerPort: 1234
        command:
        - "/main"
        - "--process-metrics"
        - "--go-metrics"
